### PR TITLE
Ts events intro

### LINKED ISSUE #19: Sub #6: Intro to Event
- [x] create the dom event page
- [x] when pressing a button a form should appear
- [x] the form should have a name, date and location
- [x] create a save button on the form and post it to the even API
- [x] populate the info to the DOM

### PR DESCRIPTION
**Pull request by treysuiter**
# Description

Please include a summary of the change and which# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #19 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing Instructions

Please describe the tests required to verify your changes. Provide instructions so PR Tester can check functionality. Please also list any relevant details for your tests

1. `git fetch --all`
2. `git checkout ts-events-intro`
3. `npm start`
4. check to see if events load, new event button appears, new form appears on new event button click, and new event is saved and populates to the dom

# Checklist:

- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] My changes generate no new warnings or errors
- [ x] I have added test instructions that prove my fix is effective or that my feature works
 issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### CODE REVIEW

**Review by chapmanjamesg — DISMISSED** [review]
does everything you described!

**Review by chapmanjamesg — DISMISSED** [review]
still looks good

**Review by chapmanjamesg — APPROVED** [review]
still looking good.

**Review by laurenriddle — APPROVED** [review]
Looks great!!

**Pull request merged**
